puts "Enter a month:"
months = gets.chomp.capitalize

case months
when "January"
  puts "Winter"
when "February"
  puts "Winter"
when "March"
  puts "Spring"
when "April"
  puts "Spring"
when "May"
  puts "Spring"
when "June"
  puts "Summer"
when "July"
  puts "Summer"
when "August"
  puts "Summer"
when "September"
  puts "Autumn"
when "October"
  puts "Autumn"
when "November"
  puts "Autumn"
when "December"
  puts "Winter"
end